server:
  port: 8081
spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      spring.json.trusted.packages: "*"
    consumer:
      group-id: heetaru-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Явно кажемо каталогу, у який клас перетворювати прилетівший JSON:
        spring.json.value.default.type: org.example.catalogservice.dto.OrderPlacedEvent
        spring.json.use.type.headers: false